### ISSUE TITLE
Can't resolve 'blob.js/blob' 

### ISSUE THREAD

**Issue by Fusselwurm** [gruppe-adler/slotting.gruppe-adler.de#1]
`npm run start` leads to 
```
ERROR in ./src/polyfills.ts                                                                     
Module not found: Error: Can't resolve 'blob.js/blob' in '/home/fusselwurm/dev/gruppe-adler/slotting.gruppe-adler.de/src'                                                                       
resolve 'blob.js/blob' in '/home/fusselwurm/dev/gruppe-adler/slotting.gruppe-adler.de/src'      
  Parsed request is a module
```

after removing the offending import from src/polyfills.ts , the project compiles. :thinking:

**Comment by chris579** [comment]
Seems like I forgot to save `blob-polyfill` in `package.json`. This just acts as a polyfill so no harm done.

**Comment by Fusselwurm** [comment]
nah, repeatedly calling `npm i` didnt do anything for me

**Comment by chris579** [comment]
Strange, need to investiagte. However, this could be removed as we're not supporting such old browers anyway.
